### ISSUE TITLE
category page needs to filter out pages

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oii-theme#1]
The category pages are including pages, not just news. Needs to just be news. Example: http://oii-test.navnorth.com/category/charter-schools-program/

I tried committing a fix that didn't display pages (https://github.com/navnorth/wp-oii-theme/commit/c42b98a8a20fdb2540e38b732a0515eedfcc1d6f) but that just messed up the nav (blank pages). Needs a custom query or a filter applied to the category query.

**Comment by johnpaulbalagolan** [comment]
fixed #1 with my latest commit to github
