### ISSUE TITLE
blue blocks extended on menu on IE10

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oii-theme#2]
tested on IE10 and the mega menu looks pretty good but looks like width of the sub-menu elements extends past end of main menu

<img width="1427" alt="ie10 blue blocks on menu" src="https://cloud.githubusercontent.com/assets/838671/8758403/5298b87c-2ca9-11e5-8499-c49b56e48c1a.png">

**Comment by johnpaulbalagolan** [comment]
fixed #2 with the latest commit to github
