### ISSUE TITLE
firefox menu display

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oii-theme#4]
Someone testing the OII site found an issue with the display of the menu on firefox. I noticed a javascript error in the console, so maybe it doesn't like a certain object being used. Please see if you can make a quick fix today or tomorrow so they can continue testing. Thanks
![screen shot 2015-08-17 at 9 25 28 am](https://cloud.githubusercontent.com/assets/838671/9307207/a62685ce-44c2-11e5-815c-93bb66a23215.png)

**Comment by johnpaulbalagolan** [comment]
fixed #4 with the latest source code committed to github. Please test it when you get a chance. I just tested it locally with fewer submenus

thanks.

**Comment by joehobson** [comment]
thanks, looks great
