### ISSUE TITLE
Order of sub-pages in Additional Info box on templates

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oii-theme#5]
The admins found a program with a page out of order in the Resources box. I checked the pages and everything is set correctly in the ordering. Here's the program. The Awards page is supposed to be 3rd:

http://oii-test.navnorth.com/what-we-do/arts/arts-in-education-model-development-and-dissemination-grants-program/

No rush on this. Hoping we can get it done by October 16th.

**Comment by johnpaulbalagolan** [comment]
Fixed #5 with the latest source committed to github.

Thanks.
